//
// rdxVerify - RDX structure and value verification
//
#include <math.h>

#include "RDX.h"
#include "abc/01.h"
#include "abc/PRO.h"

// Verification error codes (generated by ok64 utility)
con ok64 VFYBADTYPE = 0x7cf88b28d76264e;  // bad TLV type literal
con ok64 VFYBADLEN = 0x1f3e22ca355397;    // bad record length
con ok64 VFYBADUTF8 = 0x7cf88b28d79d3c8;  // invalid UTF-8
con ok64 VFYBADTERM = 0x7cf88b28d74e6d6;  // invalid term (non-Base64)
con ok64 VFYBADINT = 0x1f3e22ca3525dd;    // invalid integer encoding
con ok64 VFYBADFL = 0x7cf88b28d3d5;       // NaN or invalid float
con ok64 VFYBADREF = 0x1f3e22ca35b38f;    // invalid reference
con ok64 VFYBADNEST = 0x7cf88b28d5ce71d;  // bad nesting
con ok64 VFYBADORD = 0x1f3e22ca3586cd;    // incorrect element order
con ok64 VFYNULLOUT = 0x1f3e22ca397bf;    // empty tuple outside tuple

// RON Base64 alphabet validation
// Valid chars: 0-9 A-Z _ a-z ~
fun b8 VFYisBase64(u8 c) {
    if (c >= '0' && c <= '9') return YES;
    if (c >= 'A' && c <= 'Z') return YES;
    if (c >= 'a' && c <= 'z') return YES;
    if (c == '_' || c == '~') return YES;
    return NO;
}

// Validate term contains only RON Base64 characters, is non-empty,
// and doesn't start with a digit (would be ambiguous with integers in JDR)
fun ok64 VFYterm(u8cs term) {
    sane(u8csOK(term));
    if ($empty(term)) return VFYBADTERM;  // Terms cannot be empty
    // Terms cannot start with digit (ambiguous with integers in JDR)
    if (**term >= '0' && **term <= '9') return VFYBADTERM;
    $for(u8c, p, term) {
        if (!VFYisBase64(*p)) return VFYBADTERM;
    }
    done;
}

// Validate string with given encoding
// For escaped encodings, decode first then validate the result
fun ok64 VFYstring(u8cs str, u8 enc) {
    sane(u8csOK(str));

    if (enc == RDX_UTF_ENC_UTF8) {
        // Pure UTF-8: validate directly using abc/UTF8.h
        a_dup(u8c, s, str);
        ok64 o = utf8sValid(s);
        if (o != OK) return VFYBADUTF8;
        done;
    }

    // For escaped encodings, decode and validate
    // UTF8_DECODER_ALL decodes entire string
    UTFRecode decoder = UTABLE[enc][UTF8_DECODER_ALL];
    if (decoder == NULL) return VFYBADUTF8;

    // Decode into temporary buffer and validate
    a_pad(u8, decoded, PAGESIZE);
    a_dup(u8c, from, str);

    ok64 o = OK;
    while (!$empty(from) && o == OK) {
        o = decoder(decoded_idle, from);
        if (o == NOROOM) {
            // Validate what we have so far
            a_dup(u8c, check, decoded_datac);
            ok64 v = utf8sValid(check);
            if (v != OK) return VFYBADUTF8;
            u8bReset(decoded);
            o = OK;
        }
    }

    if (o != OK && o != END) return VFYBADUTF8;

    // Validate final decoded content
    if (!u8bEmpty(decoded)) {
        a_dup(u8c, check, decoded_datac);
        ok64 v = utf8sValid(check);
        if (v != OK) return VFYBADUTF8;
    }

    done;
}

// 60-bit limit for ref/id values (10 Base64 symbols, upper 4 bits reserved)
#define VFY_MAX_60BIT 0x0FFFFFFFFFFFFFFFUL

//
// Type-specific validators - callable from parsers
//

ok64 rdxVerifyFloat(f64 f) {
    sane(1);
    // NaN, Infinity, -0 not allowed (like JSON)
    // -0 breaks merge commutativity since 0 == -0 but bits differ
    if (isnan(f) || isinf(f) || (f == 0.0 && signbit(f))) return VFYBADFL;
    done;
}

ok64 rdxVerifyInt(i64 i) {
    sane(1);
    // Currently no restrictions on integers
    (void)i;
    done;
}

ok64 rdxVerifyRef(id128 r) {
    sane(1);
    // Check ref value is within 60-bit limit (upper 4 bits must be 0)
    if (r.seq > VFY_MAX_60BIT || r.src > VFY_MAX_60BIT) return VFYBADREF;
    done;
}

ok64 rdxVerifyId(id128 id) {
    sane(1);
    // Check id value is within 60-bit limit (upper 4 bits must be 0)
    if (id.seq > VFY_MAX_60BIT || id.src > VFY_MAX_60BIT) return VFYBADREF;
    done;
}

ok64 rdxVerifyString(u8cs str, u8 enc) { return VFYstring(str, enc); }

ok64 rdxVerifyTerm(u8cs term) { return VFYterm(term); }

// Verify TLV encoding is canonical (no overlong forms)
// rec = record start (passed by caller who saved it before parsing)
// x->next = record end (after parsing)
ok64 rdxVerifyTLV(rdxp x, u8cp rec) {
    sane(x && rec);

    u8cp start = rec;
    u8cp end = x->next;  // next advanced to record end after parsing
    size_t reclen = end - start;

    // Check TLV header form is minimal
    u8 hdr = *start;
    size_t payload = reclen - (TLVshort(hdr) ? 2 : TLVlong(hdr) ? 5 : 9);

    if (TLVhuge(hdr)) {
        test(payload > 0xFFFFFFFF, RDXOVERBAD);
    } else if (TLVlong(hdr)) {
        test(payload > 255, RDXOVERBAD);
    }

    // Check id encoding is canonical (no overlong)
    u8cp body = start + (TLVshort(hdr) ? 2 : TLVlong(hdr) ? 5 : 9);
    u8 idlen = *body;
    test(ZINT128len(x->id.seq, x->id.src) == idlen, RDXOVERBAD);

    // For FIR types, re-serialize and compare value encoding
    switch (x->type) {
        case RDX_TYPE_FLOAT:
        case RDX_TYPE_INT:
        case RDX_TYPE_REF: {
            a_pad(u8, tmp, 32);
            rdx w = {.format = RDX_FMT_TLV | RDX_FMT_WRITE};
            w.bulk = tmp;
            w.type = x->type;
            w.id = x->id;
            w.r = x->r;  // covers f, i, r union
            ok64 o = rdxWriteNextTLV(&w);
            if (o != OK) return o;
            size_t wlen = u8bDataLen(tmp);
            test(wlen == reclen, RDXOVERBAD);
            test(memcmp(start, _tmp, reclen) == 0, RDXOVERBAD);
            break;
        }
        default:
            break;
    }

    done;
}

// Verify the current element of a parsed iterator
// rec = record start (passed by caller for TLV verification)
// Does NOT recurse into containers or iterate
ok64 rdxVerify(rdxp x, u8cp rec) {
    sane(x);

    // Check type is valid
    if (x->type == 0) return OK;  // No element
    if (x->type >= RDX_TYPE_LEN) return VFYBADTYPE;

    // Format-specific canonical encoding check
    if ((x->format & ~RDX_FMT_WRITE) == RDX_FMT_TLV) {
        call(rdxVerifyTLV, x, rec);
    }

    // Check id is within 60-bit limit
    call(rdxVerifyId, x->id);

    // Verify based on type
    switch (x->type) {
        case RDX_TYPE_FLOAT:
            call(rdxVerifyFloat, x->f);
            break;
        case RDX_TYPE_INT:
            call(rdxVerifyInt, x->i);
            break;
        case RDX_TYPE_REF:
            call(rdxVerifyRef, x->r);
            break;
        case RDX_TYPE_STRING:
            call(rdxVerifyString, x->s, x->flags);
            break;
        case RDX_TYPE_TERM:
            call(rdxVerifyTerm, x->t);
            break;
        case RDX_TYPE_TUPLE:
        case RDX_TYPE_LINEAR:
        case RDX_TYPE_EULER:
        case RDX_TYPE_MULTIX:
            break;
        default:
            return VFYBADTYPE;
    }

    done;
}

// Verify container contents with ordering check for LEX containers
ok64 rdxVerifyContainer(rdxp from) {
    sane(from && !rdxWritable(from));
    rdx prev = {};
    b8 has_prev = NO;
    // LEX containers require strict ordering; Root/Tuple do not
    b8 check_order =
        from->ptype != RDX_TYPE_ROOT && from->ptype != RDX_TYPE_TUPLE;
    rdxz Z = ZTABLE[from->ptype];
    b8 is_tuple = (from->ptype == RDX_TYPE_TUPLE);
    b8 first_elem = YES;
    ok64 o = OK;
    while (o == OK) {
        u8cp rec = from->next;  // save record start before parsing
        o = rdxNext(from);
        if (o != OK) break;
        // For tuples, the first element (key) must be FIRST (non-container)
        // and must have no ID (no seq, no src)
        if (is_tuple && first_elem) {
            if (rdxTypePlex(from)) return VFYBADTYPE;
            if (from->id.seq || from->id.src) return VFYBADREF;
        }
        first_elem = NO;
        call(rdxVerify, from, rec);
        // Empty tuples are only valid inside tuples (as null placeholders)
        if (rdxIsEmptyTuple(from) && from->ptype != RDX_TYPE_TUPLE) {
            return VFYNULLOUT;
        }
        // For LEX: Z(prev, curr) must be YES (strict ordering)
        if (check_order && has_prev && !Z(&prev, from)) return VFYBADORD;
        has_prev = YES;
        prev = *from;
        if (rdxTypePlex(from)) {
            rdx cfrom = {};
            call(rdxInto, &cfrom, from);
            call(rdxVerifyContainer, &cfrom);
            call(rdxOuto, &cfrom, from);
        }
    }
    test(o == END, o);
    done;
}

// Verify entire sequence including nested elements
ok64 rdxVerifyAll(rdxp from) { return rdxVerifyContainer(from); }
