const char* io_js = "function something() {\n"
"    var TestGlobals = \"test\";\n"
"}\n"
"\n"
"something();\n"
"\n"
"io.stdin = io.StdIn()\n"
"io.stdout = io.StdOut()\n"
"io.stderr = io.StdErr()\n"
"";
