const char* io_js = "// io module initialization\n"
"//\n"
"io.stdin = io.stdIn();\n"
"io.stdout = io.stdOut();\n"
"io.stderr = io.stdErr();\n"
"\n"
"io._tq = [];\n"
"\n"
"io._tqswap = function(a, b) {\n"
"    var t = io._tq[a];\n"
"    io._tq[a] = io._tq[b];\n"
"    io._tq[b] = t;\n"
"}\n"
"\n"
"io._tqup = function() {\n"
"    var tq = io._tq;\n"
"    var a = tq.length;\n"
"    if (a == 0) return;\n"
"    a--;\n"
"    while (a>0) {\n"
"        var b = (a - 1) / 2;\n"
"        if (tq[b].ms <= tq[a].ms) break;\n"
"        io._tqswap(a, b);\n"
"        a = b;\n"
"    }\n"
"}\n"
"\n"
"io._tqdown = function () {\n"
"    var tq = io._tq;\n"
"    var n = tq.length;\n"
"    var i = 0;\n"
"    do {\n"
"        var left = 2 * i + 1;\n"
"        if (left >= n || left < i) break;\n"
"        var j = left;\n"
"        var right = left + 1;\n"
"        if (right < n && tq[j].ms > tq[right].ms) j = right;\n"
"        if (tq[i].ms <= tq[j].ms) break;\n"
"        io._tqswap(i, j);\n"
"        i = j;\n"
"    } while (1);\n"
"}\n"
"\n"
"io.timer( function (now) {\n"
"    console.log(\"TICK \"+now);\n"
"    var tq = io._tq;\n"
"    while (tq.length>0 && tq[0].ms<=now) {\n"
"        try {\n"
"            tq[0].callback();\n"
"        } catch (e) {\n"
"            io.log(e);\n"
"        }\n"
"        tq[0] = tq[io._tq.length-1];\n"
"        tq.pop();\n"
"        io._tqdown();\n"
"    }\n"
"    if (tq.length>0) {\n"
"        return tq[0].ms - now\n"
"    } else {\n"
"        return 1000*60*60*24*31; // month or \"never\"\n"
"    }\n"
"} );\n"
"\n"
"io.setTimeout = function (ms, callback) {\n"
"    io.log(\"set timeout \"+ms)\n"
"    var tq = io._tq;\n"
"    task = {ms: io.now() + ms, callback: callback};\n"
"    tq.push(task);\n"
"    io._tqup();\n"
"    io.wakeIn(ms);\n"
"}\n"
"\n"
"io.log(\"io init OK, incl timeouts\");\n"
"";
