const char* test_js = "function is_inner(av, bv, path) {\n"
"        var at = typeof av;\n"
"        var bt = typeof bv;\n"
"        if (at!=bt) \n"
"            throw path+\" \"+at+\" vs \"+bt;\n"
"        if (at!=\"object\") {\n"
"            if (av!=bv) throw path+\" \"+av+\" vs \"+bv;\n"
"            return;\n"
"        }\n"
"        if (av==null || bv==null) {\n"
"            if (av==null && bv==null) return true;\n"
"            throw path+\" \"+av+\" vs \"+bv;\n"
"        }\n"
"        is_impl(av, bv, path, 0)\n"
"}\n"
"\n"
"function is_impl(a, b, path, t) {\n"
"    for(const key in a) {\n"
"        var av = a[key]\n"
"        var bv = b[key]\n"
"        is_inner(av, bv, path + \"/\" + key)\n"
"    }\n"
"    if (t==0)\n"
"        is_impl(a, b, path, 1)\n"
"}\n"
"\n"
"test.is = function(a, b) {\n"
"    return is_inner(a, b, \"\")\n"
"}\n"
"\n"
"test.run = function() {\n"
"    var passed = 0;\n"
"    var failed = 0;\n"
"\n"
"    function check(name, fn) {\n"
"        try {\n"
"            fn();\n"
"            passed++;\n"
"        } catch (e) {\n"
"            io.log(\"FAIL \" + name + \": \" + e);\n"
"            failed++;\n"
"        }\n"
"    }\n"
"\n"
"    check(\"is: equal numbers\", function() {\n"
"        test.is(1, 1);\n"
"    });\n"
"\n"
"    check(\"is: equal strings\", function() {\n"
"        test.is(\"abc\", \"abc\");\n"
"    });\n"
"\n"
"    check(\"is: equal objects\", function() {\n"
"        test.is({a: 1, b: \"x\"}, {a: 1, b: \"x\"});\n"
"    });\n"
"\n"
"    check(\"is: nested objects\", function() {\n"
"        test.is({a: {b: 2}}, {a: {b: 2}});\n"
"    });\n"
"\n"
"    check(\"is: null equality\", function() {\n"
"        test.is(null, null);\n"
"    });\n"
"\n"
"    check(\"utf8: encode\", function() {\n"
"        var ta = utf8.Encode(\"hello\");\n"
"        test.is(ta.byteLength, 6);\n"
"    });\n"
"\n"
"    if (failed > 0) {\n"
"        io.log(\"FAILED: \" + failed + \"/\" + (passed+failed));\n"
"        io.exit();\n"
"    }\n"
"    io.log(\"PASSED: \" + passed + \"/\" + (passed+failed));\n"
"    io.exit();\n"
"}\n"
"";
