const char* test_js = "function is_inner(av, bv, path, key) {\n"
"        var at = typeof av;\n"
"        var bt = typeof bv;\n"
"        if (at!=bt) \n"
"            throw path+\" \"+key+\": \"+at+\" vs \"+bt;\n"
"        if (at!=\"object\" && av!=bv)\n"
"            throw path+\" \"+key+\": \"+av+\" vs \"+bv;\n"
"        if (av==null || bv==null) {\n"
"            if (av==null && bv==null) return true;\n"
"            throw path+\" \"+key+\": \"+av+\" vs \"+bv;\n"
"        }\n"
"        is_impl(av, bv, path + \"/\" + key, 0)\n"
"}\n"
"\n"
"function is_impl(a, b, path, t) {\n"
"    for(const key in a) {\n"
"        var av = a[key]\n"
"        var bv = b[key]\n"
"        is_inner(av, bv, path, key)\n"
"    }\n"
"    if (t==0)\n"
"        is_impl(a, b, path, 1)\n"
"}\n"
"\n"
"test.is = function(a, b) {\n"
"\n"
"    return is_inner(a, b, \"\", \"values\")\n"
"}\n"
"";
