title: librdx
permalink: /:path:output_ext

plugins:
  - jekyll-readme-index

readme_index:
  enabled: true
  remove_originals: false

exclude:
  - build*
  - pcre2-*
  - CMakeLists.txt
  - Makefile
  - "*.tar.gz"
