_a = [0-9A-Za-z];
_sp = [ \t\n\r];
_any = [0-0xff];
plain = [^\n\r \t]+;
ref = "[" plain "][" _a "]";
_em = " *" (_any - ("* "))* "* ";
em = " *" [a-z]+ "*";
inline = plain | em;
root = (_sp* inline)* _sp*;
