#include "INST.h"

#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#include "abc/FILE.h"
#include "abc/PATH.h"
#include "abc/PRO.h"
#include "tok/TOK.h"

// Resolve path of the running binary via /proc/self/exe
static ok64 INSTSelfPath(char *out, size_t outsz) {
    sane(out != NULL && outsz > 1);
    ssize_t n = readlink("/proc/self/exe", out, outsz - 1);
    test(n > 0, FAILSANITY);
    out[n] = 0;
    done;
}

// Run a popen command, discard output
static ok64 INSTRun(const char *cmd) {
    sane(cmd != NULL);
    FILE *fp = popen(cmd, "r");
    test(fp != NULL, FAILSANITY);
    char buf[256];
    while (fgets(buf, sizeof(buf), fp) != NULL) {}
    int rc = pclose(fp);
    test(rc == 0, FAILSANITY);
    done;
}

// Run a popen command, capture first line into out (trimmed)
static ok64 INSTCapture(char *out, size_t outsz, const char *cmd) {
    sane(out != NULL && outsz > 0 && cmd != NULL);
    out[0] = 0;
    FILE *fp = popen(cmd, "r");
    test(fp != NULL, FAILSANITY);
    if (fgets(out, (int)outsz, fp) == NULL) out[0] = 0;
    pclose(fp);
    size_t len = strlen(out);
    if (len > 0 && out[len - 1] == '\n') out[--len] = 0;
    done;
}

// Write .git/info/attributes with diff=spot for all files,
// merge=spot for known extensions (deduped)
static ok64 INSTWriteAttributes(const char *gitcommondir) {
    sane(gitcommondir != NULL);

    // Ensure info/ dir exists
    char infodir[FILE_PATH_MAX_LEN];
    snprintf(infodir, sizeof(infodir), "%s/info", gitcommondir);
    a_pad(u8, idbuf, FILE_PATH_MAX_LEN);
    u8cs ids = {(u8cp)infodir, (u8cp)infodir + strlen(infodir)};
    call(u8bFeed, idbuf, ids);
    call(PATHu8gTerm, PATHu8gIn(idbuf));
    // Ignore error if already exists
    FILEMakeDirP(PATHu8cgIn(idbuf));

    // Build attributes content into a buffer
    char attrpath[FILE_PATH_MAX_LEN];
    snprintf(attrpath, sizeof(attrpath), "%s/info/attributes", gitcommondir);

    // Collect unique extensions for merge
    const char *exts[256];
    int nexts = 0;
    for (int i = 0; ; i++) {
        const char *ext = TOKExtAt(i);
        if (ext == NULL) break;
        // Dedup
        b8 dup = NO;
        for (int j = 0; j < nexts; j++) {
            if (strcmp(exts[j], ext) == 0) { dup = YES; break; }
        }
        if (!dup && nexts < 256) {
            exts[nexts++] = ext;
        }
    }

    // Build content
    // Generous buffer: ~256 exts * ~30 chars each + header
    char content[16384];
    int pos = 0;
    pos += snprintf(content + pos, sizeof(content) - (size_t)pos,
                    "# Generated by spot --install\n"
                    "* diff=spot\n");
    for (int i = 0; i < nexts; i++) {
        pos += snprintf(content + pos, sizeof(content) - (size_t)pos,
                        "*.%s merge=spot\n", exts[i]);
    }

    // Write atomically
    int fd = open(attrpath, O_WRONLY | O_CREAT | O_TRUNC, 0644);
    test(fd >= 0, FAILSANITY);
    u8c *data[2] = {(u8cp)content, (u8cp)content + pos};
    ok64 o = FILEFeedall(fd, data);
    close(fd);
    test(o == OK, o);
    done;
}

// Install or update .git/hooks/post-commit
static ok64 INSTWriteHook(const char *gitcommondir) {
    sane(gitcommondir != NULL);

    char hookdir[FILE_PATH_MAX_LEN];
    snprintf(hookdir, sizeof(hookdir), "%s/hooks", gitcommondir);

    // Ensure hooks/ dir exists
    a_pad(u8, hdbuf, FILE_PATH_MAX_LEN);
    u8cs hds = {(u8cp)hookdir, (u8cp)hookdir + strlen(hookdir)};
    call(u8bFeed, hdbuf, hds);
    call(PATHu8gTerm, PATHu8gIn(hdbuf));
    FILEMakeDirP(PATHu8cgIn(hdbuf));

    char hookpath[FILE_PATH_MAX_LEN];
    snprintf(hookpath, sizeof(hookpath), "%s/hooks/post-commit", gitcommondir);

    // Check if hook already exists and contains spot --hook
    struct stat st;
    if (stat(hookpath, &st) == 0) {
        // Read existing content
        int fd = open(hookpath, O_RDONLY);
        if (fd >= 0) {
            char existing[4096];
            ssize_t n = read(fd, existing, sizeof(existing) - 1);
            close(fd);
            if (n > 0) {
                existing[n] = 0;
                if (strstr(existing, "spot --hook") != NULL) {
                    fprintf(stderr, "  hook: %s (already has spot --hook)\n",
                            hookpath);
                    done;
                }
                // Append to existing hook
                fd = open(hookpath, O_WRONLY | O_APPEND);
                test(fd >= 0, FAILSANITY);
                const char *line = "spot --hook\n";
                u8c *data[2] = {(u8cp)line, (u8cp)line + strlen(line)};
                ok64 o = FILEFeedall(fd, data);
                close(fd);
                test(o == OK, o);
                fprintf(stderr, "  hook: appended 'spot --hook' to %s\n",
                        hookpath);
                done;
            }
            // Empty file, overwrite below
        }
    }

    // Write new hook
    int fd = open(hookpath, O_WRONLY | O_CREAT | O_TRUNC, 0755);
    test(fd >= 0, FAILSANITY);
    const char *script = "#!/bin/sh\nspot --hook\n";
    u8c *data[2] = {(u8cp)script, (u8cp)script + strlen(script)};
    ok64 o = FILEFeedall(fd, data);
    close(fd);
    chmod(hookpath, 0755);
    test(o == OK, o);
    fprintf(stderr, "  hook: %s\n", hookpath);
    done;
}

ok64 INSTInstall(u8csc reporoot) {
    sane($ok(reporoot));

    // Resolve our own binary path
    char self[FILE_PATH_MAX_LEN];
    call(INSTSelfPath, self, sizeof(self));

    // Get reporoot as C string
    char root[FILE_PATH_MAX_LEN];
    size_t rlen = (size_t)$len(reporoot);
    if (rlen >= sizeof(root)) rlen = sizeof(root) - 1;
    memcpy(root, reporoot[0], rlen);
    root[rlen] = 0;

    // Get git common dir (handles worktrees)
    char cmd[FILE_PATH_MAX_LEN * 2];
    char gitcommondir[FILE_PATH_MAX_LEN];
    snprintf(cmd, sizeof(cmd), "git -C \"%s\" rev-parse --git-common-dir", root);
    call(INSTCapture, gitcommondir, sizeof(gitcommondir), cmd);
    test(gitcommondir[0] != 0, FAILSANITY);

    // Make absolute if relative
    if (gitcommondir[0] != '/') {
        char tmp[FILE_PATH_MAX_LEN];
        snprintf(tmp, sizeof(tmp), "%s/%s", root, gitcommondir);
        // Normalize: use realpath
        char *rp = realpath(tmp, gitcommondir);
        if (rp == NULL) {
            // fallback: just use the concatenated path
            snprintf(gitcommondir, sizeof(gitcommondir), "%s/%s", root, tmp);
        }
    }

    fprintf(stderr, "spot: installing into %s\n", gitcommondir);

    // Set git config: diff driver
    snprintf(cmd, sizeof(cmd),
             "git -C \"%s\" config --local diff.spot.command \"%s --gitdiff\"",
             root, self);
    call(INSTRun, cmd);
    fprintf(stderr, "  config: diff.spot.command = %s --gitdiff\n", self);

    // Set git config: merge driver name
    snprintf(cmd, sizeof(cmd),
             "git -C \"%s\" config --local merge.spot.name \"spot token merge\"",
             root);
    call(INSTRun, cmd);

    // Set git config: merge driver command
    snprintf(cmd, sizeof(cmd),
             "git -C \"%s\" config --local merge.spot.driver "
             "\"%s --merge %%O %%A %%B -o %%A\"",
             root, self);
    call(INSTRun, cmd);
    fprintf(stderr, "  config: merge.spot.driver = %s --merge %%O %%A %%B -o %%A\n",
            self);

    // Write .git/info/attributes
    call(INSTWriteAttributes, gitcommondir);
    fprintf(stderr, "  attributes: %s/info/attributes\n", gitcommondir);

    // Write post-commit hook
    call(INSTWriteHook, gitcommondir);

    fprintf(stderr, "spot: installed\n");
    done;
}
