#include "GRAF.h"

#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#include "abc/FILE.h"
#include "abc/PATH.h"
#include "abc/PRO.h"
#include "dog/TOK.h"

// Resolve path of the running binary via /proc/self/exe
static ok64 INSTSelfPath(char *out, size_t outsz) {
    sane(out != NULL && outsz > 1);
    ssize_t n = readlink("/proc/self/exe", out, outsz - 1);
    test(n > 0, FAILSANITY);
    out[n] = 0;
    done;
}

// Run a popen command, discard output
static ok64 INSTRun(const char *cmd) {
    sane(cmd != NULL);
    FILE *fp = popen(cmd, "r");
    test(fp != NULL, FAILSANITY);
    char buf[256];
    while (fgets(buf, sizeof(buf), fp) != NULL) {}
    int rc = pclose(fp);
    test(rc == 0, FAILSANITY);
    done;
}

// Run a popen command, capture first line into out (trimmed)
static ok64 INSTCapture(char *out, size_t outsz, const char *cmd) {
    sane(out != NULL && outsz > 0 && cmd != NULL);
    out[0] = 0;
    FILE *fp = popen(cmd, "r");
    test(fp != NULL, FAILSANITY);
    if (fgets(out, (int)outsz, fp) == NULL) out[0] = 0;
    pclose(fp);
    size_t len = strlen(out);
    if (len > 0 && out[len - 1] == '\n') out[--len] = 0;
    done;
}

// Write .git/info/attributes with diff=graf for all files,
// merge=graf for known extensions (deduped)
static ok64 INSTWriteAttributes(const char *gitcommondir) {
    sane(gitcommondir != NULL);

    char infodir[FILE_PATH_MAX_LEN];
    snprintf(infodir, sizeof(infodir), "%s/info", gitcommondir);
    a_pad(u8, idbuf, FILE_PATH_MAX_LEN);
    u8cs ids = {(u8cp)infodir, (u8cp)infodir + strlen(infodir)};
    call(u8bFeed, idbuf, ids);
    call(PATHu8gTerm, PATHu8gIn(idbuf));
    FILEMakeDirP(PATHu8cgIn(idbuf));

    char attrpath[FILE_PATH_MAX_LEN];
    snprintf(attrpath, sizeof(attrpath), "%s/info/attributes", gitcommondir);

    // Collect unique extensions for merge
    const char *exts[256];
    int nexts = 0;
    for (int i = 0; ; i++) {
        const char *ext = TOKExtAt(i);
        if (ext == NULL) break;
        b8 dup = NO;
        for (int j = 0; j < nexts; j++) {
            if (strcmp(exts[j], ext) == 0) { dup = YES; break; }
        }
        if (!dup && nexts < 256) {
            exts[nexts++] = ext;
        }
    }

    char content[16384];
    int pos = 0;
    pos += snprintf(content + pos, sizeof(content) - (size_t)pos,
                    "# Generated by graf --install\n"
                    "* diff=graf\n");
    for (int i = 0; i < nexts; i++) {
        pos += snprintf(content + pos, sizeof(content) - (size_t)pos,
                        "*.%s merge=graf\n", exts[i]);
    }

    a_pad(u8, apbuf, FILE_PATH_MAX_LEN);
    u8cs aps = {(u8cp)attrpath, (u8cp)attrpath + strlen(attrpath)};
    call(u8bFeed, apbuf, aps);
    call(PATHu8gTerm, PATHu8gIn(apbuf));
    int fd = -1;
    call(FILECreate, &fd, PATHu8cgIn(apbuf));
    u8csc data = {(u8cp)content, (u8cp)content + pos};
    ok64 o = FILEFeedall(fd, data);
    close(fd);
    test(o == OK, o);
    done;
}

ok64 GRAFInstall(u8cs reporoot) {
    sane($ok(reporoot));

    // Resolve our own binary path
    char self[FILE_PATH_MAX_LEN];
    call(INSTSelfPath, self, sizeof(self));

    // Get reporoot as C string
    char root[FILE_PATH_MAX_LEN];
    size_t rlen = (size_t)$len(reporoot);
    if (rlen >= sizeof(root)) rlen = sizeof(root) - 1;
    memcpy(root, reporoot[0], rlen);
    root[rlen] = 0;

    // Get git common dir (handles worktrees)
    char cmd[FILE_PATH_MAX_LEN * 2];
    char gitcommondir[FILE_PATH_MAX_LEN];
    snprintf(cmd, sizeof(cmd), "git -C \"%s\" rev-parse --git-common-dir", root);
    call(INSTCapture, gitcommondir, sizeof(gitcommondir), cmd);
    test(gitcommondir[0] != 0, FAILSANITY);

    if (gitcommondir[0] != '/') {
        char tmp[FILE_PATH_MAX_LEN];
        snprintf(tmp, sizeof(tmp), "%s/%s", root, gitcommondir);
        char *rp = realpath(tmp, gitcommondir);
        if (rp == NULL) {
            snprintf(gitcommondir, sizeof(gitcommondir), "%s/%s", root, tmp);
        }
    }

    fprintf(stderr, "graf: installing into %s\n", gitcommondir);

    // Set git config: diff driver
    snprintf(cmd, sizeof(cmd),
             "git -C \"%s\" config --local diff.graf.command \"%s --gitdiff\"",
             root, self);
    call(INSTRun, cmd);
    fprintf(stderr, "  config: diff.graf.command = %s --gitdiff\n", self);

    // Set git config: merge driver
    snprintf(cmd, sizeof(cmd),
             "git -C \"%s\" config --local merge.graf.name \"graf token merge\"",
             root);
    call(INSTRun, cmd);

    snprintf(cmd, sizeof(cmd),
             "git -C \"%s\" config --local merge.graf.driver "
             "\"%s --merge %%O %%A %%B -o %%A\"",
             root, self);
    call(INSTRun, cmd);
    fprintf(stderr, "  config: merge.graf.driver = %s --merge %%O %%A %%B -o %%A\n",
            self);

    call(INSTWriteAttributes, gitcommondir);
    fprintf(stderr, "  attributes: %s/info/attributes\n", gitcommondir);

    fprintf(stderr, "graf: installed\n");
    done;
}
