//
// Created by gritzko on 11/20/25.
//

#ifndef RDX_JDR_H
#define RDX_JDR_H
#include "RDX.h"

// len -> line number, pos -> p
typedef rdx JDRstate;

ok64 JDRlexer(JDRstate* s);

con ok64 JDRbadnest = 0x4cd6e6968ca9df8;
con ok64 JDRbad = 0x4cd6e6968;

typedef enum {
    RDX_JDR_CLASS_OPEN = 0,
    RDX_JDR_CLASS_INTER = 1,
    RDX_JDR_CLASS_FIRST = 2,
    RDX_JDR_CLASS_CLOSE = 3,
    RDX_JDR_CLASS_LEN = 4,
} RDX_JDR_CLASS;

typedef enum {
    RDX_JDR_CLASS_OPEN_OPEN = 0,
    RDX_JDR_CLASS_OPEN_INTER = 1,
    RDX_JDR_CLASS_OPEN_FIRST = 2,
    RDX_JDR_CLASS_OPEN_CLOSE = 3,
    RDX_JDR_CLASS_INTER_OPEN = 4,
    RDX_JDR_CLASS_INTER_INTER = 5,
    RDX_JDR_CLASS_INTER_FIRST = 6,
    RDX_JDR_CLASS_INTER_CLOSE = 7,
    RDX_JDR_CLASS_FIRST_OPEN = 8,
    RDX_JDR_CLASS_FIRST_INTER = 9,
    RDX_JDR_CLASS_FIRST_FIRST = 10,
    RDX_JDR_CLASS_FIRST_CLOSE = 11,
    RDX_JDR_CLASS_CLOSE_OPEN = 12,
    RDX_JDR_CLASS_CLOSE_INTER = 13,
    RDX_JDR_CLASS_CLOSE_FIRST = 14,
    RDX_JDR_CLASS_CLOSE_CLOSE = 15,
} RDX_JDR_LR1;

typedef enum {
    RDX_JDR_FORMAT_INDENT_LINES = 1,
    RDX_JDR_FORMAT_ML_STRINGS = 2,
    RDX_JDR_FORMAT_COMMA_PLEX = 4,
    RDX_JDR_FORMAT_COMMA_FIRST = 8,
    RDX_JDR_FORMAT_SPACE_PLEX = 16,
    RDX_JDR_FORMAT_SPACE_FIRST = 32,
    RDX_JDR_FORMAT_NL_PLEX = 64,
    RDX_JDR_FORMAT_NL_FIRST = 128,
    RDX_JDR_FORMAT_TRAILING_SEP = 1<<8,
    RDX_JDR_FORMAT_INLINE_TUPLES = 1<<30,
} RDX_JDR_FORMAT;

#endif  // RDX_JDR_H
